/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List everyone's batches, newest first. */
        get: operations["list_batches"];
        put?: never;
        /**
         * Start a batch. The server copies the plant's current definition into the batch and
         *     schedules the first step's tasks.
         */
        post: operations["create_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_batch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop an active batch early, for example because it molded. */
        post: operations["discard_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{id}/harvests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log what a harvested batch yielded. Log again for a second cut. */
        post: operations["log_harvest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every jar and tray in the household, unarchived ones first. */
        get: operations["list_containers"];
        put?: never;
        /** Add a jar or tray for the whole household. */
        post: operations["create_container"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_container"];
        put?: never;
        post?: never;
        /** Delete a jar or tray that has never held a batch. Archive one with history instead. */
        delete: operations["delete_container"];
        options?: never;
        head?: never;
        /** Rename, edit, archive, or restore a jar or tray. */
        patch: operations["update_container"];
        trace?: never;
    };
    "/harvests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a harvest logged by mistake. */
        delete: operations["delete_harvest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change your timezone or quiet hours. */
        patch: operations["update_me"];
        trace?: never;
    };
    "/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every plant: built-in ones, custom ones, and custom overrides of built-in ones. */
        get: operations["list_plants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plants/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_plant"];
        /**
         * Create or replace a custom plant. Using a built-in slug overrides the built-in plant for
         *     everyone on the server.
         */
        put: operations["put_plant"];
        post?: never;
        /**
         * Delete a custom plant. For an override, the built-in plant comes back. Running batches keep
         *     their copy of the definition.
         */
        delete: operations["delete_plant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["push_key"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save this device's push subscription, so reminders reach it. */
        post: operations["subscribe"];
        /** Stop sending reminders to this device. */
        delete: operations["unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test notification to all of your devices. */
        post: operations["send_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results per plant across everyone's batches: yield per gram of seed, ratings, and days to
         *     harvest.
         */
        get: operations["plant_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List open tasks on everyone's active batches, soonest first. */
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a task done. Finishing a care task schedules the next one. Finishing an advance task
         *     moves the batch into its next step, and moving into harvest ends the batch.
         */
        post: operations["complete_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push a task back. Everyone gets a new reminder when the snooze ends. */
        post: operations["snooze_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BatchDetail: {
            batch: components["schemas"]["BatchSummary"];
            /** @description Logged harvests, oldest first. */
            harvests: components["schemas"]["Harvest"][];
            notes: string;
            open_tasks: components["schemas"]["TaskView"][];
            /** @description The plant definition as it was when the batch started. */
            plant: components["schemas"]["Plant"];
            /** @description The steps the batch has been in, with actual times. */
            steps: components["schemas"]["StepRecord"][];
            /** @description Planned windows from the current step to harvest. Empty unless the batch is active. */
            upcoming: components["schemas"]["StepWindow"][];
        };
        /** @enum {string} */
        BatchStatus: "active" | "harvested" | "discarded";
        BatchSummary: {
            /** @description The container's current name. */
            container: string;
            /** @description The container's colour, as `#rrggbb`. */
            container_color?: string | null;
            /** Format: uuid */
            container_id: string;
            current_action: components["schemas"]["StepAction"];
            current_step: number;
            /** @description That user's display name. */
            grower: string;
            /**
             * Format: uuid
             * @description The user who started the batch. Everyone on the server can see and change it.
             */
            grower_id: string;
            harvest_window?: components["schemas"]["HarvestWindow"] | null;
            /** Format: uuid */
            id: string;
            plant_kind: components["schemas"]["PlantKind"];
            plant_name: string;
            plant_slug: string;
            /** Format: int32 */
            seed_g: number;
            /** Format: date-time */
            started_at: string;
            status: components["schemas"]["BatchStatus"];
            /** Format: date-time */
            step_started_at: string;
        };
        Care: {
            action: components["schemas"]["CareAction"];
            /** @example 12h */
            every: string;
        };
        /** @enum {string} */
        CareAction: "rinse" | "water" | "mist";
        Container: {
            /** Format: date-time */
            archived_at?: string | null;
            /**
             * Format: int64
             * @description How many batches this container has held, across the household.
             */
            batch_count: number;
            /** @description Lowercase `#rrggbb`, or none for clear glass and uncoloured trays. */
            color?: string | null;
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["ContainerKind"];
            name: string;
            notes: string;
            occupant?: components["schemas"]["Occupant"] | null;
        };
        /** @enum {string} */
        ContainerKind: "jar" | "tray";
        CreateBatch: {
            /**
             * Format: uuid
             * @description The jar or tray to grow in. It must not be archived or hold another active batch.
             */
            container_id: string;
            notes?: string;
            plant_slug: components["schemas"]["Slug"];
            /**
             * Format: int32
             * @description Seed weight in grams. Defaults to the plant's `seed_g`.
             */
            seed_g?: number | null;
            /**
             * Format: date-time
             * @description When the first step started. Defaults to now. Can't be in the future.
             */
            started_at?: string | null;
        };
        CreateContainer: {
            /** @description A colour like `#3b82f6`. Leave it out for clear glass. */
            color?: string | null;
            kind: components["schemas"]["ContainerKind"];
            /** @description Unique in the household, ignoring case. */
            name: string;
            notes?: string;
        };
        /** @description The body of every error response. */
        ErrorBody: {
            /** @description A stable code, like `not_found`, `invalid`, or `task_done`. */
            error: string;
            message?: string | null;
            /** @description For `invalid`, what's wrong with each field. */
            problems?: components["schemas"]["Problem"][];
        };
        Harvest: {
            /** Format: uuid */
            batch_id: string;
            /** Format: date-time */
            harvested_at: string;
            /** Format: uuid */
            id: string;
            notes: string;
            /**
             * Format: int32
             * @description 1 to 5.
             */
            rating?: number | null;
            /** Format: int32 */
            yield_g: number;
        };
        HarvestWindow: {
            /** Format: date-time */
            earliest: string;
            /** Format: date-time */
            latest: string;
        };
        LibraryEntry: {
            plant: components["schemas"]["Plant"];
            slug: components["schemas"]["Slug"];
            source: components["schemas"]["Source"];
        };
        LogHarvest: {
            /**
             * Format: date-time
             * @description Defaults to now.
             */
            harvested_at?: string | null;
            notes?: string;
            /**
             * Format: int32
             * @description 1 to 5.
             */
            rating?: number | null;
            /**
             * Format: int32
             * @description Grams harvested.
             */
            yield_g: number;
        };
        /** @description The active batch in a container. */
        Occupant: {
            /** Format: uuid */
            batch_id: string;
            grower: string;
            /**
             * Format: uuid
             * @description Who started the batch.
             */
            grower_id: string;
            plant_name: string;
        };
        Plant: {
            kind: components["schemas"]["PlantKind"];
            name: string;
            name_lat?: string | null;
            /**
             * Format: int32
             * @description Suggested seed weight for one jar or tray, in grams.
             */
            seed_g?: number | null;
            steps: components["schemas"]["Step"][];
        };
        /** @enum {string} */
        PlantKind: "sprout" | "microgreen";
        /** @description How one plant has done across everyone's harvested batches with at least one harvest logged. */
        PlantStats: {
            /**
             * Format: double
             * @description From the batch's start to its first harvest.
             */
            average_days: number;
            /**
             * Format: double
             * @description Over harvests that have a rating.
             */
            average_rating?: number | null;
            /** Format: int64 */
            batches: number;
            plant_name: string;
            plant_slug: string;
            /** Format: int64 */
            seed_g: number;
            /** Format: int64 */
            yield_g: number;
            /**
             * Format: double
             * @description Grams harvested per gram of seed.
             */
            yield_ratio: number;
        };
        /** @description One thing wrong with a plant definition. `path` points at the field, like `steps[1].care[0]`. */
        Problem: {
            message: string;
            path: string;
        };
        PushKey: {
            /**
             * @description The VAPID public key, as base64url, for `pushManager.subscribe`. Null when push
             *     notifications are off on this server.
             */
            public_key?: string | null;
        };
        /** @description Quiet hours in a user's local time. `end` before `start` means they run past midnight. */
        QuietHours: {
            /** @example 07:00 */
            end: string;
            /** @example 22:00 */
            start: string;
        };
        /**
         * @description A plant's id, like `mung-bean`. Lowercase letters, digits, and single hyphens, at most 64
         *     characters.
         * @example mung-bean
         */
        Slug: string;
        SnoozeTask: {
            /**
             * Format: date-time
             * @description When to remind you again. Within the next week.
             */
            until: string;
        };
        /** @enum {string} */
        Source: "builtin" | "custom" | "override";
        Step: {
            action: components["schemas"]["StepAction"];
            /** @description Chores that repeat while the batch is in this step. */
            care?: components["schemas"]["Care"][];
            /**
             * @description When the step is overdue. Leave it out for a step with a fixed length.
             * @example 12h
             */
            duration_max?: string | null;
            /**
             * @description When the step can end at the earliest. Required for every step except harvest.
             * @example 8h
             */
            duration_min?: string | null;
            note?: string | null;
        };
        /** @enum {string} */
        StepAction: "soak" | "sprout" | "blackout" | "light" | "harvest";
        StepRecord: {
            action: components["schemas"]["StepAction"];
            /** Format: date-time */
            ended_at?: string | null;
            /** Format: date-time */
            started_at: string;
            step_index: number;
        };
        /** @description When a step should start if every step before it takes its shortest or longest time. */
        StepWindow: {
            action: components["schemas"]["StepAction"];
            /** Format: date-time */
            earliest_start: string;
            /** Format: date-time */
            latest_start: string;
            step_index: number;
        };
        /** @description The JSON a browser's `PushSubscription.toJSON()` gives. */
        SubscriptionBody: {
            endpoint: string;
            keys: components["schemas"]["SubscriptionKeys"];
        };
        SubscriptionKeys: {
            auth: string;
            p256dh: string;
        };
        /** @description Serializes as `{ "kind": "advance", "action": "light" }` or `{ "kind": "care", "action": "rinse" }`. */
        TaskAction: {
            /** @description Move the batch into the next step, whose action this is. */
            action: components["schemas"]["StepAction"];
            /** @enum {string} */
            kind: "advance";
        } | {
            action: components["schemas"]["CareAction"];
            /** @enum {string} */
            kind: "care";
        };
        TaskView: components["schemas"]["TaskAction"] & {
            /** Format: uuid */
            batch_id: string;
            container: string;
            container_color?: string | null;
            /** Format: date-time */
            due_at: string;
            grower: string;
            /**
             * Format: uuid
             * @description The user who started the batch.
             */
            grower_id: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            overdue_at?: string | null;
            plant_name: string;
            /**
             * Format: date-time
             * @description Set while the task is snoozed. `due_at` already counts the snooze.
             */
            snoozed_until?: string | null;
            step_index: number;
        };
        TestResult: {
            /** @description Subscriptions removed because the push service no longer knows them. */
            removed: number;
            /** @description Devices the push service accepted the message for. */
            sent: number;
        };
        UnsubscribeBody: {
            endpoint: string;
        };
        /** @description Fields to change. Leave a field out to keep it. */
        UpdateContainer: {
            /** @description Archive or restore. Archived containers can't take new batches. */
            archived?: boolean | null;
            /** @description A colour like `#3b82f6`, or null to remove it. */
            color?: string | null;
            kind?: components["schemas"]["ContainerKind"] | null;
            name?: string | null;
            notes?: string | null;
        };
        /**
         * @description Settings to change. Leave a field out to keep it. Send `"quiet_hours": null` to turn quiet
         *     hours off.
         */
        UpdateMe: {
            quiet_hours?: components["schemas"]["QuietHours"] | null;
            /** @description An IANA timezone, like `Europe/Budapest`. */
            timezone?: string | null;
        };
        User: {
            display_name: string;
            email?: string | null;
            /** Format: uuid */
            id: string;
            quiet_hours?: components["schemas"]["QuietHours"] | null;
            /** @description An IANA timezone, like `Europe/Budapest`. Quiet hours and "today" follow it. */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_batches: {
        parameters: {
            query?: {
                /** @description Only return batches with this status. */
                status?: components["schemas"]["BatchStatus"];
                /** @description Only return batches grown in this jar or tray. */
                container_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSummary"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBatch"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDetail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The jar or tray holds another active batch (`container_in_use`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_batch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDetail"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    discard_batch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discarded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The batch isn't active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    log_harvest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogHarvest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Harvest"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The batch isn't harvested yet (`batch_not_harvested`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_containers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Container"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_container: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContainer"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Container"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The name is empty, too long, or taken */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_container: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Container"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_container: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It has held batches (`container_has_history`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_container: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContainer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Container"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Archiving a container with an active batch (`container_in_use`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_harvest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_plants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntry"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_plant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntry"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    put_plant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Plant"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntry"];
                };
            };
            /** @description The body isn't a plant definition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The definition breaks a rule */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_plant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No custom plant has this slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    push_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushKey"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionBody"];
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribeBody"];
            };
        };
        responses: {
            /** @description Removed, or it wasn't saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    send_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Push notifications are off on this server (`push_disabled`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    plant_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantStats"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: {
                /** @description Only return tasks due at or before this time, like the end of the user's day. */
                due_before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    complete_task: {
        parameters: {
            query?: {
                /**
                 * @description When it was done, for ticks made offline that sync later. Defaults to now. At most a week
                 *     ago, and not in the future.
                 */
                done_at?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The task is already done (`task_done`), or its batch has moved on (`batch_not_active`, `stale_task`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `done_at` is in the future or more than a week ago */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    snooze_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnoozeTask"];
            };
        };
        responses: {
            /** @description Snoozed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The task is done or its batch has ended */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The time is in the past or more than a week away */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
