[package]
name = "baby-greens-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.23.1"
dotenvy = "0.15.7"
humantime = "2.4.0"
jiff = { version = "0.2", features = ["tzdb-bundle-always"] }
openidconnect = "4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls-ring", "postgres", "macros", "migrate", "uuid", "time", "json"] }
thiserror = "2.0.21"
time = { version = "0.3.55", features = ["formatting", "macros", "parsing", "serde"] }
tokio = { version = "1.53.2", features = ["full"] }
tower-http = { version = "0.7.1", features = ["trace", "fs"] }
tower-sessions = { version = "0.14", default-features = false, features = ["axum-core"] }
tower-sessions-sqlx-store = { version = "0.15", features = ["postgres"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"
utoipa = { version = "6.0.0", features = ["time", "uuid"] }
utoipa-axum = "0.3.0"
utoipa-scalar = { version = "0.4.0", features = ["axum"] }
uuid = { version = "1.27.0", features = ["serde"] }
web-push-native = "0.5"
